generation:
  ndim: 1
  ngen_mc: 100000
  ngen_true: 10000
  of_niter: 5
  random_seed: 1
  use_poisson_fluctuations_around_total: true
model:
  activation: !!python/name:__main__.parametric_gelu ''
  beta: 4
parameters:
  mc:
    cov: !!python/object/apply:numpy._core.multiarray._reconstruct
      args:
      - &id001 !!python/name:numpy.ndarray ''
      - !!python/tuple
        - 0
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple
        - 1
        - 1
      - &id002 !!python/object/apply:numpy.dtype
        args:
        - f4
        - false
        - true
        state: !!python/tuple
        - 3
        - <
        - null
        - null
        - null
        - -1
        - -1
        - 0
      - false
      - !!binary |
        AACAPw==
    mu: !!python/object/apply:numpy._core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple
        - 0
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple
        - 1
      - *id002
      - false
      - !!binary |
        AAAAAA==
    rho:
    - !!python/object/apply:numpy._core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple
        - 0
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple
        - 0
      - *id002
      - false
      - !!binary ""
    sig: !!python/object/apply:numpy._core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple
        - 0
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple
        - 1
      - *id002
      - false
      - !!binary |
        AACAPw==
  resolution:
    sf: 1.0
    values: !!python/object/apply:numpy._core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple
        - 0
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple
        - 1
      - *id002
      - false
      - !!binary |
        AAAAPw==
  'true':
    cov: !!python/object/apply:numpy._core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple
        - 0
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple
        - 1
        - 1
      - *id002
      - false
      - !!binary |
        KFxPPw==
    mu: !!python/object/apply:numpy._core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple
        - 0
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple
        - 1
      - *id002
      - false
      - !!binary |
        zcxMPg==
    rho:
    - !!python/object/apply:numpy._core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple
        - 0
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple
        - 0
      - *id002
      - false
      - !!binary ""
    sig: !!python/object/apply:numpy._core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple
        - 0
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple
        - 1
      - *id002
      - false
      - !!binary |
        ZmZmPw==
regularization:
  l1reg_activation: 0.0
  l1reg_bias: 0.0
  l1reg_kernel: 0.0
  l2reg_activation: 0.0
  l2reg_bias: 0.0
  l2reg_kernel: 0.0
timestamp: '2025-09-06T16:28:55.877896'
training:
  batch_size: 10000
  epochs: 50
  learning_rate: 0.0005
  n_models_to_ensemble: 10
  patience: -1
  restore_best_weights: false
